[package]
name = "calc_rs"
version = "0.1.0"
authors = ["cgm616 <cgm616@me.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
stdweb = "0.4"
pest = "1.0.2"
pest_derive = "*"
lazy_static = "1.4"